version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-job-app
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache/laravel.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    working_dir: /var/www/html
    networks:
      - laravel-job-network

  db:
    image: mariadb:11
    container_name: laravel-job-db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_job
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata_job:/var/lib/mysql
    networks:
      - laravel-job-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-job-phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    depends_on:
      - db
    networks:
      - laravel-job-network

volumes:
  dbdata_job:

networks:
  laravel-job-network:
    driver: bridge